obj-y := start.o main.o exception.o exception_asm.o heap.o injector.o libadt.o nvram.o block_dev.o gpt.o fat.o config_parser.o cache.o
obj-$(CONFIG_BLOCK_DEV_VIRTIO) += virtio_blk.o
obj-$(CONFIG_BLOCK_DEV_UFSHC) += ufshc_blk.o
obj-y += ../common/
obj-y += dlmalloc/